### ISSUE TITLE
Interactive function planned?

### ISSUE THREAD

**Issue by k-aito** [b1ek/hey#4]
Hello @b1ek 

I'm not sure you preferred and issue here or on your self-hosted git, but if you prefer on your self-hosted git, just tell me.

I discovered your code today and it's really cool. Do you have plans to add an interactive mode so that it's possible to correct the LLM?

Cheers

**Comment by b1ek** [comment]
> I'm not sure you preferred and issue here

no preference. the only limitation is that PRs have to be submitted via git.blek.codes.

> Do you have plans to add an interactive mode so that it's possible to correct the LLM?

i've thought of making a TUI interface, but thats just too hard for me to maintain, i dont really want to spend a lot of energy on this.

another thing would be to create a file per terminal with a state which `hey` will write to, and restore history from that file each time a message is sent

**Comment by k-aito** [comment]
Helllo

I think the history way would be enough for most people.

If I get time, I would try to dig a little to make something interactive, but it would be my first time doing Rust so better not have too much hope ^^

**Comment by mrgick** [comment]
Hello

I did some research

To work history needed:
- on POST https://duckduckgo.com/duckchat/v1/chat needed to include list messages in payload like [{"role": "user", "content": "First prompt"}, {"role": "assistant", "content": "some_result"}, {"role": "user", "content": "Second prompt"},]
- Also needed to always get working x-vqd-4 :
  1. Simulate browser (get country.json)
  2. GET https://duckduckgo.com/duckchat/v1/status with header headers["x-vqd-accept"] = "1" - we update x-vqd-4
  3. Make POST to chat - update  x-vqd-4  if we get it
  4. Make new GET status - update  x-vqd-4 if we get it
  5. Goto iii (with updated history array)

Unfortunately, I don't know enough rust, to implement this.
But, I know Python - and implemented this in [my repo](https://github.com/mrgick/duckduckgo-chat-ai/blob/main/duck_chat/api.py#L105)

To test my repo needed python 3.12
```pip install https://github.com/mrgick/duckduckgo-chat-ai/archive/master.zip```
```python -m duck_chat```

**Comment by b1ek** [comment]
i've implemented this in 0.2.0 release

@mrgick sorry, i didn't see your message before i implemented my own. i did pretty much what you said, i think its all explained in my original article. you can also have as many messages as you want, like its not limited to a `"user-ai-"*n`/ message pattern, it can be like a `"user-user-user-ai"` message. probably an overlook from the DDG side

also a new `vqd-4` is always returned in the header on `/v1/chat`, you shouldn't always request it from `/v1/status`, but you need to send it for some heartbeat-like DDG protocol
